[provider]
cluster = "localnet"
wallet = "~/.config/miraland/id.json"

[programs.localnet]
basic_1 = "AnchoL61Nt2sgXvrXYUHxRQgEgaJ4ueMg5xJQVyFJ5Gs"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
