name: No Caching Tests

on:
  push:
    branches:
      - main

jobs:
  no-caching-tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      cache: false
      miraland_cli_version: 1.18.0
      node_version: 17.0.1
      cargo_profile: release
      anchor_binary_name: anchor-binary-no-caching
