name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      cache: true
      miraland_cli_version: 1.18.0
      node_version: 17.0.1
      cargo_profile: debug
      anchor_binary_name: anchor-binary
